name: Deploy PHP Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sync Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_HETZNER }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY_HETZNER }}
          source: "."
          target: "/home/userwww/web/webreadyplan.com/public_html"
          strip_components: 1

      - name: Final Setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_HETZNER }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY_HETZNER }}
          command_timeout: 90m
          script: |
            # Remove .git and .github directories
            sudo rm -rf /home/userwww/web/webreadyplan.com/public_html/.git
            sudo rm -rf /home/userwww/web/webreadyplan.com/public_html/.github
            sudo rm -rf /home/userwww/web/webreadyplan.com/public_html/.DS_Store
            
            # Set permissions to the web directory
            chmod -R 775 /home/userwww/web/webreadyplan.com/public_html/storage
            chmod -R 775 /home/userwww/web/webreadyplan.com/public_html/bootstrap/cache
            chown -R userwww:www-data /home/userwww/web/webreadyplan.com/public_html/storage
            chown -R userwww:www-data /home/userwww/web/webreadyplan.com/public_html/bootstrap/cache
            # Clear and cache configurations
            cd /home/userwww/web/webreadyplan.com/public_html
            php artisan config:clear
            php artisan config:cache
            # Clear and cache routes
            php artisan route:clear
            php artisan route:cache
            # Clear and cache views
            php artisan view:clear
            php artisan view:cache
